POST http://localhost:5000/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "The",
    "lastName": "Hulk",
    "email": "hulk@destroy.com",
    "password": "Alldestroy",
    "birthday": "1954-02-18",
    "gender": "male"
}

# {
#     "firstName": "John",
#     "lastName": "Travolta",
#     "email": "travolta@john.com",
#     "password": "whereyou",
#     "birthday": "1954-02-18",
#     "gender": "male"
# }